workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/

stages:
  - package

package-linux-deb:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DEB

package-linux-rpm:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=RPM

package-osx-pkg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/login.keychain-db
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/ecsec.keychain-db
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=PKG

package-osx-dmg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DMG

notarize-osx-pkg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  dependencies:
    - "package-osx-pkg"
    - "package-osx-dmg"
  script:
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/login.keychain-db
    - PKG_FILE_PATH=$(find packager/richclient-packager/target/jpackage/ -name 'Open-eCard-App-*.pkg')
    - xcrun notarytool submit ${PKG_FILE_PATH}
        --keychain-profile "oec-installers"
        --wait
  needs: [ "package-osx-pkg", "package-osx-dmg" ]
  rules:
    - when: manual

package-win:
  stage: package
  tags:
    - "win"
  variables:
    WIN_KEYSTORE: C:\gitlab-runner\assets\openecard_cs.p12
  artifacts:
    paths:
      - packager/richclient-packager/target/iscc
  script:
    - .\mvnw.cmd install -DskipTests -Ddesktop-package
    - $EXE_FILE_PATH = $(Get-Childitem
        -Path .\packager\richclient-packager\target\iscc\
        -Include Open-eCard-App-*.exe
        -File -Recurse -ErrorAction SilentlyContinue | Format-Wide Name  | Out-String).Trim()                                          
    - signtool.exe sign 
        /debug 
        /p ${WIN_KEYCHAIN_PW}
        /f "${WIN_KEYSTORE}"
        /tr http://sha256timestamp.ws.symantec.com/sha256/timestamp
        /td SHA256
        /fd SHA256
        .\packager\richclient-packager\target\iscc\$EXE_FILE_PATH
