workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - compile
  - test
  - analyze
  - package
  - post-package
  - publish

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_USER_HOME: "$CI_PROJECT_DIR/.m2"
  OEC_DOCKER_CACHE: "oec-cache"
  OEC_OSX_CACHE: "oec-macos-cache"
  OEC_WIN_CACHE: "oec-win-cache"

include:
- '/ci/compile.yml'
- '/ci/test.yml'
- '/ci/sast.yml'
- '/ci/package-linux.yml'
- '/ci/package-osx.yml'
- '/ci/package-win.yml'
- '/ci/package-ios-framework.yml'
- '/ci/post-package.yml'
- '/ci/publish.yml'
