workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - compile
  - test
  - analyze
  - package
  - post-package
  - deploy
  - publish

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  OEC_DOCKER_CACHE: "oec-cache"
  OEC_OSX_CACHE: "oec-macos-cache"
  OEC_WIN_CACHE: "oec-win-cache"

include:
- '/.gitlab-ci.d/cache.yml'
- '/.gitlab-ci.d/compile.yml'
- '/.gitlab-ci.d/test.yml'
- '/.gitlab-ci.d/sast.yml'
- '/.gitlab-ci.d/package-linux.yml'
- '/.gitlab-ci.d/package-osx.yml'
- '/.gitlab-ci.d/package-win.yml'
- '/.gitlab-ci.d/package-ios-framework.yml'
- '/.gitlab-ci.d/post-package.yml'
- '/.gitlab-ci.d/deploy.yml'
- '/.gitlab-ci.d/publish.yml'
