workflow:
  rules:
    #- if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "v2-installers"

stages:
  - package

package-linux-deb:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DEB

package-linux-rpm:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=RPM

package-osx-pkg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=PKG

package-osx-dmg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DMG

package-win:
  stage: package
  tags:
    - "win"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package
