workflow:
  rules:
    #- if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "v2-installers"

stages:
  - package

package-linux-deb:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DEB

package-linux-rpm:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "linux"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=RPM

package-osx-pkg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/login.keychain-db
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/ecsec.keychain-db
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=PKG
    # Notarization Process
    - PKG_FILE_PATH=$(find packager/richclient-packager/target/jpackage/ -name 'Open-eCard-App-*.pkg')
    - xcrun altool --notarize-app
      --primary-bundle-id "org.openecard.versioncheck.MainLoader"
      --username "${MAC_OS_NOTARIZATION_USERNAME}"
      --password "${MAC_OS_NOTARIZATION_PASSWORD}"
      --asc-provider "72RMQ6K75Z"
      --file $PKG_FILE_PATH

package-osx-dmg:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  variables:
    JAVA_HOME: /Users/ecsec-ci/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package -Dpackage.type=DMG

package-win:
  stage: package
  tags:
    - "win"
  artifacts:
    paths:
      - packager/richclient-packager/target/jpackage
  script:
    - mvn install -DskipTests -Ddesktop-package
