deploy-mvn-artifacts:
  stage: deploy
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "docker-exec"
  cache:
    - key: "$OEC_JAVA_CACHE_KEY"
      paths: !reference [ .cache-gradle-base, paths ]
      policy: pull
    - key: "$OEC_JAVA_TMP_CACHE_KEY"
      paths: [ .cache-gradle-builds, paths ]
      policy: pull
  script:
    - VERSION=$(echo "${CI_COMMIT_TAG}" | cut -c 2-)
    - ./gradlew publish -Pversion=${VERSION}
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
