deploy-mvn-artifacts:
  stage: deploy
  image: docker.io/mobiledevops/android-sdk-image:34.0.1
  tags:
    - "podman"
  cache:
    - key: "$OEC_JAVA_CACHE_KEY"
      paths: !reference [ .cache-gradle-base, paths ]
      policy: pull
    - key: "$OEC_JAVA_TMP_CACHE_KEY"
      paths: [ .cache-gradle-builds, paths ]
      policy: pull
  script:
    - !reference [.versioning, script]
    - ./gradlew publish -Pversion=${VERSION}
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/

deploy-mvn-artifacts-mr:
  stage: deploy
  image: docker.io/mobiledevops/android-sdk-image:34.0.1
  tags:
    - "podman"
  cache:
    - key: "$OEC_JAVA_CACHE_KEY"
      paths: !reference [ .cache-gradle-base, paths ]
      policy: pull
    - key: "$OEC_JAVA_TMP_CACHE_KEY"
      paths: [ .cache-gradle-builds, paths ]
      policy: pull
  script:
    - !reference [.versioning, script]
    - ./gradlew publish -Pversion=${VERSION}
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"
