package-osx:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  cache:
  - key: "$OEC_JAVA_CACHE_KEY"
    paths: !reference [ .cache-gradle-base, paths ]
    policy: pull
  - key: "$OEC_JAVA_TMP_CACHE_KEY"
    paths: [ .cache-gradle-builds, paths ]
    policy: pull
  artifacts:
    name: 'OeC-Installer-PKG'
    paths:
      - clients/richclient/build/dist
  script:
    - ./gradlew packageMac
  needs: [ "compile" ]
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual

notarize-osx:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  dependencies:
    - "package-osx"
  artifacts:
    name: 'OeC-Installer'
    paths:
      - clients/richclient/build/dist
  script:
    - security unlock-keychain -p ${MAC_OS_KEYCHAIN_PW} /Users/ecsec-ci/Library/Keychains/login.keychain-db
    - DMG_FILE_PATH=$(find clients/richclient/build/dist -name 'Open-eCard-App-*.dmg')
    - PKG_FILE_PATH=$(find clients/richclient/build/dist -name 'Open-eCard-App-*.pkg')
    - xcrun notarytool submit ${DMG_FILE_PATH}
        --keychain-profile "oec-installers"
        --wait
    - xcrun notarytool submit ${PKG_FILE_PATH}
        --keychain-profile "oec-installers"
        --wait
    - xcrun stapler staple ${PKG_FILE_PATH}
    - xcrun stapler staple ${DMG_FILE_PATH}
  needs: [ "package-osx" ]
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual
