package-ios-framework:
  stage: package
  tags:
    - "mac"
    - "dev-cert"
  cache:
    key: "$OEC_OSX_CACHE"
    paths:
      - .m2/wrapper/dists
      - .m2/repository/
      - .mvn/wrapper/maven-wrapper.jar
    policy: pull-push
  artifacts:
    name: 'OpenEcard-CocoaPod'
    paths:
      - OpenEcard.xcframework/
      - LICENSE.*
      - LICENSE
  script:
    - ./gradlew buildIosFramework
    - mv clients/ios-framework/build/robovm/OpenEcard.xcframework OpenEcard.xcframework/
    - cp LICENSE.GPL LICENSE
  needs: []
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual
