package-win:
  stage: package
  tags:
    - "win"
  artifacts:
    name: 'OeC-Installer-EXE'
    paths:
      - clients/richclient/build/dist/
  script:
    - .\gradlew.bat packageWin
    - $EXE_FILE_PATH = $(Get-Childitem
        -Path .\clients\richclient\build\dist
        -Include Open-eCard-App-*.exe
        -File -Recurse -ErrorAction SilentlyContinue | Format-Wide Name  | Out-String).Trim()                                          
    - signtool.exe sign 
        /debug 
        /p ${WIN_KEYSTORE_PW}
        /f "${WIN_KEYSTORE}"
        /tr http://sha256timestamp.ws.symantec.com/sha256/timestamp
        /td SHA256
        /fd SHA256
        .\clients\richclient\build\dist\$EXE_FILE_PATH
  needs: [ "compile" ]
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual
