collect-installers:
  stage: post-package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "docker-exec"
  artifacts:
    name: 'OeC-Installers'
    paths:
      - "*.deb"
      - "*.rpm"
      - "*.dmg"
      - "*.pkg"
      - "*.exe"
  script:
    - >-
      cp  clients/richclient/build/dist/jpackage/*.pkg \
          clients/richclient/build/dist/jpackage/*.dmg \
          clients/richclient/build/dist/jpackage/*.deb \
          clients/richclient/build/dist/jpackage/*.rpm \
          clients/richclient/build/dist/iscc/*.exe \
          .
  dependencies:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  needs:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_MERGE_REQUEST_IID
