collect-installers:
  stage: post-package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "docker-exec"
  artifacts:
    name: 'OeC-Installers'
    paths:
      - "*.deb"
      - "*.rpm"
      - "*.dmg"
      - "*.pkg"
      - "*.exe"
  script:
    - >-
      cp  packager/richclient-packager/target/jpackage/*.pkg \
          packager/richclient-packager/target/jpackage/*.dmg \
          packager/richclient-packager/target/jpackage/*.deb \
          packager/richclient-packager/target/jpackage/*.rpm \
          packager/richclient-packager/target/iscc/*.exe \
          .
  dependencies:
    - "package-linux-deb"
    - "package-linux-rpm"
    - "package-osx-pkg"
    - "package-osx-dmg"
    - "package-win"
  needs:
    - "package-linux-deb"
    - "package-linux-rpm"
    - "package-osx-pkg"
    - "package-osx-dmg"
    - "package-win"
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual
