collect-installers:
  stage: post-package
  image: docker.io/alpine:latest
  tags:
    - "podman"
  artifacts:
    name: 'OeC-Installers'
    paths:
      - "*.deb"
      - "*.rpm"
      - "*.dmg"
      - "*.pkg"
      - "*.exe"
  script:
    - >-
      cp  clients/richclient/build/dist/*.pkg \
          clients/richclient/build/dist/*.dmg \
          clients/richclient/build/dist/*.deb \
          clients/richclient/build/dist/*.rpm \
          clients/richclient/build/dist/*.exe \
          .
  dependencies:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  needs:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_MERGE_REQUEST_IID
