test:
  stage: test
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:latest
  tags:
    - "podman"
  cache:
    - key: "$OEC_JAVA_CACHE_KEY"
      paths: !reference [ .cache-gradle-base, paths ]
      policy: pull-push
    - key: "$OEC_JAVA_TMP_CACHE_KEY"
      paths: [ .cache-gradle-builds, paths ]
      policy: pull-push
  artifacts:
    reports:
      junit:
        - "**/build/jacoco-report/jacoco.xml"
        - "**/build/test-results/test/TEST-*.xml"
  script:
    - ./gradlew check
  needs: [ "compile" ]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"
  allow_failure: true
